### ISSUE TITLE
[BUG] Weird behaviour while using backlinks

### ISSUE THREAD

**Issue by reisnobre** [renerocksai/telekasten.nvim#95]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
Fresh installion of the plugin, nothing customized at all.
Running on macOs, but besides that everthing is as recommended. 

**To Reproduce**
1. Start nvim
2. Go to a note that has backlinks
3. Call the backlink function
4. A weird path appears on the telescope searchbox instead of the filename correctly.

**Expected behavior**
The list of files that links to the current file should appear

**Screenshots**

<img width="1786" alt="Screen Shot 2022-02-21 at 23 11 13" src="https://user-images.githubusercontent.com/12832066/155050402-b6ec6198-bb7d-43b5-ac3a-7ef6f46f4935.png">

**Operating system (please complete the following information):**
 - macOs

**Comment by bergtholdt** [comment]
Looks like the the full path of the file is included in the grep string. Maybe you telekasten home is not set properly in your initialization.

I just had a problem where backlinks did not work and the reason was that I used obsidian to when creating the files and it does not use subdirectories for the links. In my telekasten config, however, I had  subdirs_in_links = true, which caused the the backlinks search to include the subfolder and no files were shown. Once I fixed the config, chaning  subdirs_in_links = false, I properly get backlinks.

**Comment by wakatara** [comment]
Setting `subdirs_in_links = false` also corrected this problem for me when I was playing around with (even though there *was* a subdir in the link, so not sure if that's the right behaviour or not. 

But thanks @bergtholdt for the pointer!

**Comment by lambtho12** [comment]
@reisnobre Considering the inputs of @bergtholdt and @wakatara , should we still keep this open?

**Comment by alexander-gabriel** [comment]
this fails for me due to the regexp formatting and escaping of brackets.
I can't find information in the telescope git on whether or not it supports regexp search patterns or how to enable/disable regexp parsing of search terms.

may be relevant: I'm using the telescope-fzf-native extension

**Comment by lambtho12** [comment]
@alexander-gabriel any new information on that? Does the issue still persist? Did you find a solution?

**Comment by fingolfin19** [comment]
I have the same issue on Windows. When subdir_in_links is true, the entire path of the current file is included in the backlink regex. Setting subdir_in_links to false results in the correct pattern, but backlinks should add subdirs starting from the home directory.

Home for me should be set correctly:

```lua
		{
			"renerocksai/telekasten.nvim",
			cmd = "Telekasten",
			opts = {
				home = vim.fn.expand("C:/Users/me/Documents/Notes"), -- Put the name of your notes directory here
    },
},
			},
```

Find notes and find daily notes commands start at the correct directory.
